//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SdsClientLibraries {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SdsClientLibraries.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a stream with a secondary index..
        /// </summary>
        internal static string AddingSecondaryIndex {
            get {
                return ResourceManager.GetString("AddingSecondaryIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s add some Tags and Metadata to our stream:.
        /// </summary>
        internal static string AddTagsMetadata {
            get {
                return ResourceManager.GetString("AddTagsMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -------------------------------------------------------------
        ///  _________    .___           _______  ______________________
        /// /   _____/  __| _/______     \      \ \_   _____/\__    ___/
        /// \_____  \  / __ |/  ___/     /   |   \ |    __)_   |    |   
        /// /        \/ /_/ |\___ \     /    |    \|        \  |    |   
        ////_______  /\____ /____  &gt; /\ \____|__  /_______  /  |____|   
        ///        \/      \/    \/  \/         \/        \/            
        ///-------------------------------------------------------------.
        /// </summary>
        internal static string Banner {
            get {
                return ResourceManager.GetString("Banner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleaning up.
        /// </summary>
        internal static string CleaningUp {
            get {
                return ResourceManager.GetString("CleaningUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete!.
        /// </summary>
        internal static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating an SdsStream off of type with compound index.
        /// </summary>
        internal static string CreatingCompoundStream {
            get {
                return ResourceManager.GetString("CreatingCompoundStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating an SdsType with a compound index.
        /// </summary>
        internal static string CreatingCompoundType {
            get {
                return ResourceManager.GetString("CreatingCompoundType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating an SdsStream.
        /// </summary>
        internal static string CreatingStream {
            get {
                return ResourceManager.GetString("CreatingStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating an SdsType.
        /// </summary>
        internal static string CreatingType {
            get {
                return ResourceManager.GetString("CreatingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default (Continuous) requesting data starting at index location &apos;1&apos;, where we have not entered data, SDS will interpolate a value for this property and then return entered values:.
        /// </summary>
        internal static string DefaultContinuous {
            get {
                return ResourceManager.GetString("DefaultContinuous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All values deleted successfully!.
        /// </summary>
        internal static string DeletedSuccessfully {
            get {
                return ResourceManager.GetString("DeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting stream.
        /// </summary>
        internal static string DeletingStream {
            get {
                return ResourceManager.GetString("DeletingStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting stream views.
        /// </summary>
        internal static string DeletingStreamViews {
            get {
                return ResourceManager.GetString("DeletingStreamViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting types.
        /// </summary>
        internal static string DeletingTypes {
            get {
                return ResourceManager.GetString("DeletingTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting values from the SdsStream.
        /// </summary>
        internal static string DeletingValues {
            get {
                return ResourceManager.GetString("DeletingValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting all events.
        /// </summary>
        internal static string GettingAll {
            get {
                return ResourceManager.GetString("GettingAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting latest event.
        /// </summary>
        internal static string GettingLatest {
            get {
                return ResourceManager.GetString("GettingLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting replaced events.
        /// </summary>
        internal static string GettingReplaced {
            get {
                return ResourceManager.GetString("GettingReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting Sampled Values:.
        /// </summary>
        internal static string GettingSampled {
            get {
                return ResourceManager.GetString("GettingSampled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting table events.
        /// </summary>
        internal static string GettingTable {
            get {
                return ResourceManager.GetString("GettingTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting updated events.
        /// </summary>
        internal static string GettingUpdated {
            get {
                return ResourceManager.GetString("GettingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is some of our data as it is stored on the server:.
        /// </summary>
        internal static string HereIsSomeData {
            get {
                return ResourceManager.GetString("HereIsSomeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inserting data.
        /// </summary>
        internal static string InsertingData {
            get {
                return ResourceManager.GetString("InsertingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata associated with: {0}.
        /// </summary>
        internal static string MetadataAssociatedWith {
            get {
                return ResourceManager.GetString("MetadataAssociatedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifying a stream to have a secondary index..
        /// </summary>
        internal static string ModifyingSecondaryIndex {
            get {
                return ResourceManager.GetString("ModifyingSecondaryIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can override this behavior on a property by property basis, here we override the Radians property instructing Sds not to interpolate..
        /// </summary>
        internal static string OverrideRadiansInterpolate {
            get {
                return ResourceManager.GetString("OverrideRadiansInterpolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing a secondary index from a stream..
        /// </summary>
        internal static string RemovingSecondaryIndex {
            get {
                return ResourceManager.GetString("RemovingSecondaryIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing events.
        /// </summary>
        internal static string ReplacingEvents {
            get {
                return ResourceManager.GetString("ReplacingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDS will interpolate a value for each index asked for (5,14,23,32):.
        /// </summary>
        internal static string SdsInterpolate {
            get {
                return ResourceManager.GetString("SdsInterpolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDS can interpolate or extrapolate data at an index location where data does not explicitly exist:.
        /// </summary>
        internal static string SdsInterpolateOrExtrapolate {
            get {
                return ResourceManager.GetString("SdsInterpolateOrExtrapolate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDS will only return the values where the radians are less than 50:.
        /// </summary>
        internal static string SdsRadiansLessThan50 {
            get {
                return ResourceManager.GetString("SdsRadiansLessThan50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDS will now return the default value for the data type:.
        /// </summary>
        internal static string SdsReturnDefaultValue {
            get {
                return ResourceManager.GetString("SdsReturnDefaultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDS can return a sample of your data population to show trends..
        /// </summary>
        internal static string SdsSampleTrends {
            get {
                return ResourceManager.GetString("SdsSampleTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SdsStreamViews.
        /// </summary>
        internal static string SdsStreamViews {
            get {
                return ResourceManager.GetString("SdsStreamViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SdsStreamViews can also convert certain types of data, here we return integers where the original values were doubles:.
        /// </summary>
        internal static string StreamViewConvertData {
            get {
                return ResourceManager.GetString("StreamViewConvertData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is our explicit mapping, note SdsStreamViewMap will return all properties of the Source Type, even those without a corresponding Target property:.
        /// </summary>
        internal static string StreamViewExplicitMapping {
            get {
                return ResourceManager.GetString("StreamViewExplicitMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can query SDS to return the SdsStreamViewMap for our SdsStreamView, here is the one generated automatically:.
        /// </summary>
        internal static string StreamViewQuerySds {
            get {
                return ResourceManager.GetString("StreamViewQuerySds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifying a StreamView with an SdsType of the same shape returns values that are automatically mapped to the target SdsType&apos;s properties:.
        /// </summary>
        internal static string StreamViewSameShape {
            get {
                return ResourceManager.GetString("StreamViewSameShape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will now update the stream type based on the streamview.
        /// </summary>
        internal static string StreamViewUpdateType {
            get {
                return ResourceManager.GetString("StreamViewUpdateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags associated with: {0}.
        /// </summary>
        internal static string TagsAssociatedWith {
            get {
                return ResourceManager.GetString("TagsAssociatedWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating events.
        /// </summary>
        internal static string UpdatingEvents {
            get {
                return ResourceManager.GetString("UpdatingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Data:.
        /// </summary>
        internal static string WindowData {
            get {
                return ResourceManager.GetString("WindowData", resourceCulture);
            }
        }
    }
}
