trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/Authentication/ClientCredentialFlow/DotNet'

pr:
  branches:
    include:
      - master
  paths:
    include:
      - '/basic_samples/Authentication/ClientCredentialFlow/DotNet'

variables:
  - template: '/miscellaneous/build_templates/variables.yml'
  - name: projPath
    value: '/basic_samples/Authentication/ClientCredentialFlow/DotNet/ClientCredentialFlow'
  - name: CredFile
    value: appsettings.json
  - name: CredFileLibrary
    value: product-readiness.auth_cc_dotnet.json
  - name: testPath
    value: '/basic_samples/Authentication/ClientCredentialFlow/DotNet/ClientCredentialFlowTest'
  - name: covStream
    value: Auth_CC_DotNet

jobs:
  - job: Tests
    strategy:
      matrix:
        linux:
          imageName: ubuntu-16.04
        windows:
          imageName: vs2017-win2016
    pool:
      vmImage: $(imageName)
    steps:
      - template: '/miscellaneous/build_templates/config.yml'
        parameters:
          fileOriginal: $(CredFile)
          fileLibrary: $(CredFileLibrary)
          projPath: $(projPath)

      - script: |
          dotnet restore
          dotnet msbuild -p:HIGHENTROPYVA=true
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/
        displayName: 'Build app'

      - script: |
          dotnet restore
          dotnet test
        workingDirectory: $(Build.SourcesDirectory)$(testPath)/
        displayName: 'Run tests'

  - template: '/miscellaneous/build_templates/coverity.yml'
    parameters:
      covAgent: $(covAgent)
      covAuthPath: $(covAuthPath)
      covFolder: $(covFolder)
      covPath: $(covPath)
      covServer: $(covServer)
      covStream: $(covStream)
      projPath: $(projPath)

  - template: '/miscellaneous/build_templates/binskim.yml'
    parameters:
      projPath: $(projPath)
