parameters:
  agent: ''
  authPath: ''
  folder: ''
  path: ''
  server: ''
  projPath: ''
  name: ''

jobs:
  - job: Coverity
    pool:
      name: 00-OSIManaged-Test
      demands: USERNAME -equals $(agent)

    steps:
      - script: if not exist $(folder) mkdir $(folder)
        workingDirectory: $(projPath)
        displayName: Make dir
        continueOnError: true

      - script: "$(path)cov-build" --dir . --no-command --fs-capture-search ../
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/$(folder)
        displayName: Build

      - script: "$(path)cov-analyze" --dir .
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/$(folder)
        displayName: Analyze

      - script: "$(path)cov-commit-defects" --stream "Engineering Incubation - $(name)" --host $(server) --https-port 8443 --auth-key-file "$(authPath)" --dir .
        workingDirectory: $(Build.SourcesDirectory)$(projPath)/$(folder)
        displayName: Upload
